#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSystem.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QSystem")]
	public partial class ServerContractDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public ServerContractDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QSystemConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ServerContractDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServerContractDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServerContractDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServerContractDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WebApp> WebApp
		{
			get
			{
				return this.GetTable<WebApp>();
			}
		}
		
		public System.Data.Linq.Table<StorageBlob_Web> StorageBlob_Web
		{
			get
			{
				return this.GetTable<StorageBlob_Web>();
			}
		}
		
		public System.Data.Linq.Table<SqlServer> SqlServer
		{
			get
			{
				return this.GetTable<SqlServer>();
			}
		}
		
		public System.Data.Linq.Table<Mysql> Mysql
		{
			get
			{
				return this.GetTable<Mysql>();
			}
		}
		
		public System.Data.Linq.Table<WebSolution> WebSolution
		{
			get
			{
				return this.GetTable<WebSolution>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebApp")]
	public partial class WebApp
	{
		
		private string _WebAppType;
		
		private string _WebName;
		
		private string _PlanType;
		
		private string _Scale;
		
		private string _Configuration;
		
		private string _Unit;
		
		private System.Nullable<double> _OSSA;
		
		private System.Nullable<double> _monthly;
		
		private string _开发注意;
		
		public WebApp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAppType", DbType="NVarChar(255)")]
		public string WebAppType
		{
			get
			{
				return this._WebAppType;
			}
			set
			{
				if ((this._WebAppType != value))
				{
					this._WebAppType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebName", DbType="NVarChar(255)")]
		public string WebName
		{
			get
			{
				return this._WebName;
			}
			set
			{
				if ((this._WebName != value))
				{
					this._WebName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanType", DbType="NVarChar(255)")]
		public string PlanType
		{
			get
			{
				return this._PlanType;
			}
			set
			{
				if ((this._PlanType != value))
				{
					this._PlanType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scale", DbType="NVarChar(255)")]
		public string Scale
		{
			get
			{
				return this._Scale;
			}
			set
			{
				if ((this._Scale != value))
				{
					this._Scale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Configuration", DbType="NVarChar(255)")]
		public string Configuration
		{
			get
			{
				return this._Configuration;
			}
			set
			{
				if ((this._Configuration != value))
				{
					this._Configuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(255)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSA", DbType="Float")]
		public System.Nullable<double> OSSA
		{
			get
			{
				return this._OSSA;
			}
			set
			{
				if ((this._OSSA != value))
				{
					this._OSSA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthly", DbType="Float")]
		public System.Nullable<double> monthly
		{
			get
			{
				return this._monthly;
			}
			set
			{
				if ((this._monthly != value))
				{
					this._monthly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_开发注意", DbType="NVarChar(255)")]
		public string 开发注意
		{
			get
			{
				return this._开发注意;
			}
			set
			{
				if ((this._开发注意 != value))
				{
					this._开发注意 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[StorageBlob-Web]")]
	public partial class StorageBlob_Web
	{
		
		private string _WebAppType;
		
		private string _WebStorageType;
		
		private string _Storage;
		
		private string _StorageType;
		
		private string _redundancyType;
		
		private string _range;
		
		private string _Unit;
		
		private System.Nullable<double> _OSSA;
		
		private string _开发注意;
		
		public StorageBlob_Web()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAppType", DbType="NVarChar(255)")]
		public string WebAppType
		{
			get
			{
				return this._WebAppType;
			}
			set
			{
				if ((this._WebAppType != value))
				{
					this._WebAppType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebStorageType", DbType="NVarChar(255)")]
		public string WebStorageType
		{
			get
			{
				return this._WebStorageType;
			}
			set
			{
				if ((this._WebStorageType != value))
				{
					this._WebStorageType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Storage", DbType="NVarChar(255)")]
		public string Storage
		{
			get
			{
				return this._Storage;
			}
			set
			{
				if ((this._Storage != value))
				{
					this._Storage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorageType", DbType="NVarChar(255)")]
		public string StorageType
		{
			get
			{
				return this._StorageType;
			}
			set
			{
				if ((this._StorageType != value))
				{
					this._StorageType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_redundancyType", DbType="NVarChar(255)")]
		public string redundancyType
		{
			get
			{
				return this._redundancyType;
			}
			set
			{
				if ((this._redundancyType != value))
				{
					this._redundancyType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_range", DbType="NVarChar(255)")]
		public string range
		{
			get
			{
				return this._range;
			}
			set
			{
				if ((this._range != value))
				{
					this._range = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(255)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSA", DbType="Float")]
		public System.Nullable<double> OSSA
		{
			get
			{
				return this._OSSA;
			}
			set
			{
				if ((this._OSSA != value))
				{
					this._OSSA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_开发注意", DbType="NVarChar(255)")]
		public string 开发注意
		{
			get
			{
				return this._开发注意;
			}
			set
			{
				if ((this._开发注意 != value))
				{
					this._开发注意 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SqlServer")]
	public partial class SqlServer
	{
		
		private string _WebAppType;
		
		private string _SQLDB;
		
		private string _DTUOReDTU;
		
		private string _SqlServerLevel;
		
		private string _SqlServerType;
		
		private string _configuration;
		
		private string _RestorePoint_;
		
		private string _WhenBack;
		
		private System.Nullable<double> _OSSA;
		
		private System.Nullable<double> _monthly;
		
		private string _开发注意;
		
		public SqlServer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAppType", DbType="NVarChar(255)")]
		public string WebAppType
		{
			get
			{
				return this._WebAppType;
			}
			set
			{
				if ((this._WebAppType != value))
				{
					this._WebAppType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQLDB", DbType="NVarChar(255)")]
		public string SQLDB
		{
			get
			{
				return this._SQLDB;
			}
			set
			{
				if ((this._SQLDB != value))
				{
					this._SQLDB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTUOReDTU", DbType="NVarChar(255)")]
		public string DTUOReDTU
		{
			get
			{
				return this._DTUOReDTU;
			}
			set
			{
				if ((this._DTUOReDTU != value))
				{
					this._DTUOReDTU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqlServerLevel", DbType="NVarChar(255)")]
		public string SqlServerLevel
		{
			get
			{
				return this._SqlServerLevel;
			}
			set
			{
				if ((this._SqlServerLevel != value))
				{
					this._SqlServerLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqlServerType", DbType="NVarChar(255)")]
		public string SqlServerType
		{
			get
			{
				return this._SqlServerType;
			}
			set
			{
				if ((this._SqlServerType != value))
				{
					this._SqlServerType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_configuration", DbType="NVarChar(255)")]
		public string configuration
		{
			get
			{
				return this._configuration;
			}
			set
			{
				if ((this._configuration != value))
				{
					this._configuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[RestorePoint ]", Storage="_RestorePoint_", DbType="NVarChar(255)")]
		public string RestorePoint_
		{
			get
			{
				return this._RestorePoint_;
			}
			set
			{
				if ((this._RestorePoint_ != value))
				{
					this._RestorePoint_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhenBack", DbType="NVarChar(255)")]
		public string WhenBack
		{
			get
			{
				return this._WhenBack;
			}
			set
			{
				if ((this._WhenBack != value))
				{
					this._WhenBack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSA", DbType="Float")]
		public System.Nullable<double> OSSA
		{
			get
			{
				return this._OSSA;
			}
			set
			{
				if ((this._OSSA != value))
				{
					this._OSSA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthly", DbType="Float")]
		public System.Nullable<double> monthly
		{
			get
			{
				return this._monthly;
			}
			set
			{
				if ((this._monthly != value))
				{
					this._monthly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_开发注意", DbType="NVarChar(255)")]
		public string 开发注意
		{
			get
			{
				return this._开发注意;
			}
			set
			{
				if ((this._开发注意 != value))
				{
					this._开发注意 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mysql")]
	public partial class Mysql
	{
		
		private string _WebAppType;
		
		private string _MySqlType;
		
		private string _configuration;
		
		private string _RestorePoint_;
		
		private string _Unit;
		
		private System.Nullable<double> _OSSA;
		
		private System.Nullable<double> _monthly;
		
		public Mysql()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAppType", DbType="NVarChar(255)")]
		public string WebAppType
		{
			get
			{
				return this._WebAppType;
			}
			set
			{
				if ((this._WebAppType != value))
				{
					this._WebAppType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MySqlType", DbType="NVarChar(255)")]
		public string MySqlType
		{
			get
			{
				return this._MySqlType;
			}
			set
			{
				if ((this._MySqlType != value))
				{
					this._MySqlType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_configuration", DbType="NVarChar(255)")]
		public string configuration
		{
			get
			{
				return this._configuration;
			}
			set
			{
				if ((this._configuration != value))
				{
					this._configuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[RestorePoint ]", Storage="_RestorePoint_", DbType="NVarChar(255)")]
		public string RestorePoint_
		{
			get
			{
				return this._RestorePoint_;
			}
			set
			{
				if ((this._RestorePoint_ != value))
				{
					this._RestorePoint_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(255)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSA", DbType="Float")]
		public System.Nullable<double> OSSA
		{
			get
			{
				return this._OSSA;
			}
			set
			{
				if ((this._OSSA != value))
				{
					this._OSSA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monthly", DbType="Float")]
		public System.Nullable<double> monthly
		{
			get
			{
				return this._monthly;
			}
			set
			{
				if ((this._monthly != value))
				{
					this._monthly = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebSolution")]
	public partial class WebSolution
	{
		
		private string _PrimaryKey;
		
		private string _ProductName;
		
		private string _ProductType;
		
		private string _Configuration;
		
		private string _Unit;
		
		private System.Nullable<decimal> _Number;
		
		private System.Nullable<decimal> _OSSAunitCost;
		
		private System.Nullable<decimal> _OSSPunitCost;
		
		private System.Nullable<decimal> _OSSAMonthlyCost;
		
		private System.Nullable<decimal> _OSSPMonthlyCost;
		
		private string _Remark;
		
		public WebSolution()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryKey", DbType="NVarChar(255)")]
		public string PrimaryKey
		{
			get
			{
				return this._PrimaryKey;
			}
			set
			{
				if ((this._PrimaryKey != value))
				{
					this._PrimaryKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(255)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductType", DbType="NVarChar(255)")]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Configuration", DbType="NVarChar(255)")]
		public string Configuration
		{
			get
			{
				return this._Configuration;
			}
			set
			{
				if ((this._Configuration != value))
				{
					this._Configuration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSAunitCost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OSSAunitCost
		{
			get
			{
				return this._OSSAunitCost;
			}
			set
			{
				if ((this._OSSAunitCost != value))
				{
					this._OSSAunitCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSPunitCost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OSSPunitCost
		{
			get
			{
				return this._OSSPunitCost;
			}
			set
			{
				if ((this._OSSPunitCost != value))
				{
					this._OSSPunitCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSAMonthlyCost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OSSAMonthlyCost
		{
			get
			{
				return this._OSSAMonthlyCost;
			}
			set
			{
				if ((this._OSSAMonthlyCost != value))
				{
					this._OSSAMonthlyCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSSPMonthlyCost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OSSPMonthlyCost
		{
			get
			{
				return this._OSSPMonthlyCost;
			}
			set
			{
				if ((this._OSSPMonthlyCost != value))
				{
					this._OSSPMonthlyCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(255)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
